// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Request
	RequestEcho
	RequestFlush
	RequestInfo
	RequestSetOption
	RequestInitChain
	RequestQuery
	RequestBeginBlock
	RequestCheckTx
	RequestDeliverTx
	RequestEndBlock
	RequestCommit
	ResponseUpload
	IPFSReponse
	Response
	ResponseException
	ResponseEcho
	ResponseFlush
	ResponseInfo
	ResponseSetOption
	ResponseInitChain
	ResponseQuery
	ResponseBeginBlock
	ResponseCheckTx
	ResponseDeliverTx
	ResponseEndBlock
	ResponseCommit
	ConsensusParams
	BlockSize
	TxSize
	BlockGossip
	Header
	BlockID
	PartSetHeader
	Validator
	Evidence
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import common "github.com/tendermint/tmlibs/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeType int32

const (
	CodeType_OK CodeType = 0
	// General response codes, 0 ~ 99
	CodeType_InternalError     CodeType = 1
	CodeType_EncodingError     CodeType = 2
	CodeType_BadNonce          CodeType = 3
	CodeType_Unauthorized      CodeType = 4
	CodeType_InsufficientFunds CodeType = 5
	CodeType_UnknownRequest    CodeType = 6
	// Reserved for BCFS, 300 ~ 399
	CodeType_BCFSDuplicateAddress CodeType = 101
	CodeType_BCFSEncodingError    CodeType = 102
	CodeType_BCFSInvalidInput     CodeType = 106
	CodeType_BCFSInvalidOutput    CodeType = 107
	CodeType_BCFSInvalidPubKey    CodeType = 108
	CodeType_BCFSInvalidSignature CodeType = 110
	CodeType_BCFSUnknownAddress   CodeType = 111
	CodeType_BCFSUnknownPubKey    CodeType = 112
	CodeType_BCFSUnknownPlugin    CodeType = 113
	CodeType_BCFSBeginUploadOK    CodeType = 114
)

var CodeType_name = map[int32]string{
	0:   "OK",
	1:   "InternalError",
	2:   "EncodingError",
	3:   "BadNonce",
	4:   "Unauthorized",
	5:   "InsufficientFunds",
	6:   "UnknownRequest",
	101: "BCFSDuplicateAddress",
	102: "BCFSEncodingError",
	106: "BCFSInvalidInput",
	107: "BCFSInvalidOutput",
	108: "BCFSInvalidPubKey",
	110: "BCFSInvalidSignature",
	111: "BCFSUnknownAddress",
	112: "BCFSUnknownPubKey",
	113: "BCFSUnknownPlugin",
	114: "BCFSBeginUploadOK",
}
var CodeType_value = map[string]int32{
	"OK":                   0,
	"InternalError":        1,
	"EncodingError":        2,
	"BadNonce":             3,
	"Unauthorized":         4,
	"InsufficientFunds":    5,
	"UnknownRequest":       6,
	"BCFSDuplicateAddress": 101,
	"BCFSEncodingError":    102,
	"BCFSInvalidInput":     106,
	"BCFSInvalidOutput":    107,
	"BCFSInvalidPubKey":    108,
	"BCFSInvalidSignature": 110,
	"BCFSUnknownAddress":   111,
	"BCFSUnknownPubKey":    112,
	"BCFSUnknownPlugin":    113,
	"BCFSBeginUploadOK":    114,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}
func (CodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	// Types that are valid to be assigned to Value:
	//	*Request_Echo
	//	*Request_Flush
	//	*Request_Info
	//	*Request_SetOption
	//	*Request_InitChain
	//	*Request_Query
	//	*Request_BeginBlock
	//	*Request_CheckTx
	//	*Request_DeliverTx
	//	*Request_EndBlock
	//	*Request_Commit
	Value isRequest_Value `protobuf_oneof:"value"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isRequest_Value interface {
	isRequest_Value()
}

type Request_Echo struct {
	Echo *RequestEcho `protobuf:"bytes,2,opt,name=echo,oneof"`
}
type Request_Flush struct {
	Flush *RequestFlush `protobuf:"bytes,3,opt,name=flush,oneof"`
}
type Request_Info struct {
	Info *RequestInfo `protobuf:"bytes,4,opt,name=info,oneof"`
}
type Request_SetOption struct {
	SetOption *RequestSetOption `protobuf:"bytes,5,opt,name=set_option,json=setOption,oneof"`
}
type Request_InitChain struct {
	InitChain *RequestInitChain `protobuf:"bytes,6,opt,name=init_chain,json=initChain,oneof"`
}
type Request_Query struct {
	Query *RequestQuery `protobuf:"bytes,7,opt,name=query,oneof"`
}
type Request_BeginBlock struct {
	BeginBlock *RequestBeginBlock `protobuf:"bytes,8,opt,name=begin_block,json=beginBlock,oneof"`
}
type Request_CheckTx struct {
	CheckTx *RequestCheckTx `protobuf:"bytes,9,opt,name=check_tx,json=checkTx,oneof"`
}
type Request_DeliverTx struct {
	DeliverTx *RequestDeliverTx `protobuf:"bytes,19,opt,name=deliver_tx,json=deliverTx,oneof"`
}
type Request_EndBlock struct {
	EndBlock *RequestEndBlock `protobuf:"bytes,11,opt,name=end_block,json=endBlock,oneof"`
}
type Request_Commit struct {
	Commit *RequestCommit `protobuf:"bytes,12,opt,name=commit,oneof"`
}

func (*Request_Echo) isRequest_Value()       {}
func (*Request_Flush) isRequest_Value()      {}
func (*Request_Info) isRequest_Value()       {}
func (*Request_SetOption) isRequest_Value()  {}
func (*Request_InitChain) isRequest_Value()  {}
func (*Request_Query) isRequest_Value()      {}
func (*Request_BeginBlock) isRequest_Value() {}
func (*Request_CheckTx) isRequest_Value()    {}
func (*Request_DeliverTx) isRequest_Value()  {}
func (*Request_EndBlock) isRequest_Value()   {}
func (*Request_Commit) isRequest_Value()     {}

func (m *Request) GetValue() isRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Request) GetEcho() *RequestEcho {
	if x, ok := m.GetValue().(*Request_Echo); ok {
		return x.Echo
	}
	return nil
}

func (m *Request) GetFlush() *RequestFlush {
	if x, ok := m.GetValue().(*Request_Flush); ok {
		return x.Flush
	}
	return nil
}

func (m *Request) GetInfo() *RequestInfo {
	if x, ok := m.GetValue().(*Request_Info); ok {
		return x.Info
	}
	return nil
}

func (m *Request) GetSetOption() *RequestSetOption {
	if x, ok := m.GetValue().(*Request_SetOption); ok {
		return x.SetOption
	}
	return nil
}

func (m *Request) GetInitChain() *RequestInitChain {
	if x, ok := m.GetValue().(*Request_InitChain); ok {
		return x.InitChain
	}
	return nil
}

func (m *Request) GetQuery() *RequestQuery {
	if x, ok := m.GetValue().(*Request_Query); ok {
		return x.Query
	}
	return nil
}

func (m *Request) GetBeginBlock() *RequestBeginBlock {
	if x, ok := m.GetValue().(*Request_BeginBlock); ok {
		return x.BeginBlock
	}
	return nil
}

func (m *Request) GetCheckTx() *RequestCheckTx {
	if x, ok := m.GetValue().(*Request_CheckTx); ok {
		return x.CheckTx
	}
	return nil
}

func (m *Request) GetDeliverTx() *RequestDeliverTx {
	if x, ok := m.GetValue().(*Request_DeliverTx); ok {
		return x.DeliverTx
	}
	return nil
}

func (m *Request) GetEndBlock() *RequestEndBlock {
	if x, ok := m.GetValue().(*Request_EndBlock); ok {
		return x.EndBlock
	}
	return nil
}

func (m *Request) GetCommit() *RequestCommit {
	if x, ok := m.GetValue().(*Request_Commit); ok {
		return x.Commit
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Echo)(nil),
		(*Request_Flush)(nil),
		(*Request_Info)(nil),
		(*Request_SetOption)(nil),
		(*Request_InitChain)(nil),
		(*Request_Query)(nil),
		(*Request_BeginBlock)(nil),
		(*Request_CheckTx)(nil),
		(*Request_DeliverTx)(nil),
		(*Request_EndBlock)(nil),
		(*Request_Commit)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// value
	switch x := m.Value.(type) {
	case *Request_Echo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Echo); err != nil {
			return err
		}
	case *Request_Flush:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Flush); err != nil {
			return err
		}
	case *Request_Info:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *Request_SetOption:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetOption); err != nil {
			return err
		}
	case *Request_InitChain:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitChain); err != nil {
			return err
		}
	case *Request_Query:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case *Request_BeginBlock:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BeginBlock); err != nil {
			return err
		}
	case *Request_CheckTx:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckTx); err != nil {
			return err
		}
	case *Request_DeliverTx:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeliverTx); err != nil {
			return err
		}
	case *Request_EndBlock:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EndBlock); err != nil {
			return err
		}
	case *Request_Commit:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Value has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 2: // value.echo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestEcho)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Echo{msg}
		return true, err
	case 3: // value.flush
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestFlush)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Flush{msg}
		return true, err
	case 4: // value.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestInfo)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Info{msg}
		return true, err
	case 5: // value.set_option
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestSetOption)
		err := b.DecodeMessage(msg)
		m.Value = &Request_SetOption{msg}
		return true, err
	case 6: // value.init_chain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestInitChain)
		err := b.DecodeMessage(msg)
		m.Value = &Request_InitChain{msg}
		return true, err
	case 7: // value.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestQuery)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Query{msg}
		return true, err
	case 8: // value.begin_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestBeginBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Request_BeginBlock{msg}
		return true, err
	case 9: // value.check_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestCheckTx)
		err := b.DecodeMessage(msg)
		m.Value = &Request_CheckTx{msg}
		return true, err
	case 19: // value.deliver_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestDeliverTx)
		err := b.DecodeMessage(msg)
		m.Value = &Request_DeliverTx{msg}
		return true, err
	case 11: // value.end_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestEndBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Request_EndBlock{msg}
		return true, err
	case 12: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestCommit)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Commit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// value
	switch x := m.Value.(type) {
	case *Request_Echo:
		s := proto.Size(x.Echo)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Flush:
		s := proto.Size(x.Flush)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Info:
		s := proto.Size(x.Info)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SetOption:
		s := proto.Size(x.SetOption)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_InitChain:
		s := proto.Size(x.InitChain)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Query:
		s := proto.Size(x.Query)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BeginBlock:
		s := proto.Size(x.BeginBlock)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CheckTx:
		s := proto.Size(x.CheckTx)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_DeliverTx:
		s := proto.Size(x.DeliverTx)
		n += proto.SizeVarint(19<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_EndBlock:
		s := proto.Size(x.EndBlock)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Commit:
		s := proto.Size(x.Commit)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RequestEcho struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RequestEcho) Reset()                    { *m = RequestEcho{} }
func (m *RequestEcho) String() string            { return proto.CompactTextString(m) }
func (*RequestEcho) ProtoMessage()               {}
func (*RequestEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RequestFlush struct {
}

func (m *RequestFlush) Reset()                    { *m = RequestFlush{} }
func (m *RequestFlush) String() string            { return proto.CompactTextString(m) }
func (*RequestFlush) ProtoMessage()               {}
func (*RequestFlush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RequestInfo struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *RequestInfo) Reset()                    { *m = RequestInfo{} }
func (m *RequestInfo) String() string            { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()               {}
func (*RequestInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// nondeterministic
type RequestSetOption struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *RequestSetOption) Reset()                    { *m = RequestSetOption{} }
func (m *RequestSetOption) String() string            { return proto.CompactTextString(m) }
func (*RequestSetOption) ProtoMessage()               {}
func (*RequestSetOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestSetOption) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestSetOption) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestInitChain struct {
	Validators    []*Validator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
	AppStateBytes []byte       `protobuf:"bytes,2,opt,name=app_state_bytes,json=appStateBytes,proto3" json:"app_state_bytes,omitempty"`
}

func (m *RequestInitChain) Reset()                    { *m = RequestInitChain{} }
func (m *RequestInitChain) String() string            { return proto.CompactTextString(m) }
func (*RequestInitChain) ProtoMessage()               {}
func (*RequestInitChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RequestInitChain) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *RequestInitChain) GetAppStateBytes() []byte {
	if m != nil {
		return m.AppStateBytes
	}
	return nil
}

type RequestQuery struct {
	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Height int64  `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Prove  bool   `protobuf:"varint,4,opt,name=prove" json:"prove,omitempty"`
}

func (m *RequestQuery) Reset()                    { *m = RequestQuery{} }
func (m *RequestQuery) String() string            { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()               {}
func (*RequestQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RequestQuery) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RequestQuery) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RequestQuery) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RequestQuery) GetProve() bool {
	if m != nil {
		return m.Prove
	}
	return false
}

type RequestBeginBlock struct {
	Hash                []byte      `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header              *Header     `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	AbsentValidators    []int32     `protobuf:"varint,3,rep,packed,name=absent_validators,json=absentValidators" json:"absent_validators,omitempty"`
	ByzantineValidators []*Evidence `protobuf:"bytes,4,rep,name=byzantine_validators,json=byzantineValidators" json:"byzantine_validators,omitempty"`
}

func (m *RequestBeginBlock) Reset()                    { *m = RequestBeginBlock{} }
func (m *RequestBeginBlock) String() string            { return proto.CompactTextString(m) }
func (*RequestBeginBlock) ProtoMessage()               {}
func (*RequestBeginBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestBeginBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RequestBeginBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RequestBeginBlock) GetAbsentValidators() []int32 {
	if m != nil {
		return m.AbsentValidators
	}
	return nil
}

func (m *RequestBeginBlock) GetByzantineValidators() []*Evidence {
	if m != nil {
		return m.ByzantineValidators
	}
	return nil
}

type RequestCheckTx struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *RequestCheckTx) Reset()                    { *m = RequestCheckTx{} }
func (m *RequestCheckTx) String() string            { return proto.CompactTextString(m) }
func (*RequestCheckTx) ProtoMessage()               {}
func (*RequestCheckTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RequestCheckTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type RequestDeliverTx struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *RequestDeliverTx) Reset()                    { *m = RequestDeliverTx{} }
func (m *RequestDeliverTx) String() string            { return proto.CompactTextString(m) }
func (*RequestDeliverTx) ProtoMessage()               {}
func (*RequestDeliverTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RequestDeliverTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type RequestEndBlock struct {
	Height int64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *RequestEndBlock) Reset()                    { *m = RequestEndBlock{} }
func (m *RequestEndBlock) String() string            { return proto.CompactTextString(m) }
func (*RequestEndBlock) ProtoMessage()               {}
func (*RequestEndBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RequestEndBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RequestCommit struct {
}

func (m *RequestCommit) Reset()                    { *m = RequestCommit{} }
func (m *RequestCommit) String() string            { return proto.CompactTextString(m) }
func (*RequestCommit) ProtoMessage()               {}
func (*RequestCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ResponseUpload struct {
	Codetype CodeType `protobuf:"varint,1,opt,name=codetype,enum=types.CodeType" json:"codetype,omitempty"`
	Message  string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ResponseUpload) Reset()                    { *m = ResponseUpload{} }
func (m *ResponseUpload) String() string            { return proto.CompactTextString(m) }
func (*ResponseUpload) ProtoMessage()               {}
func (*ResponseUpload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ResponseUpload) GetCodetype() CodeType {
	if m != nil {
		return m.Codetype
	}
	return CodeType_OK
}

func (m *ResponseUpload) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type IPFSReponse struct {
	Codetype CodeType `protobuf:"varint,1,opt,name=codetype,enum=types.CodeType" json:"codetype,omitempty"`
	Message  string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *IPFSReponse) Reset()                    { *m = IPFSReponse{} }
func (m *IPFSReponse) String() string            { return proto.CompactTextString(m) }
func (*IPFSReponse) ProtoMessage()               {}
func (*IPFSReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IPFSReponse) GetCodetype() CodeType {
	if m != nil {
		return m.Codetype
	}
	return CodeType_OK
}

func (m *IPFSReponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	// Types that are valid to be assigned to Value:
	//	*Response_Exception
	//	*Response_Echo
	//	*Response_Flush
	//	*Response_Info
	//	*Response_SetOption
	//	*Response_InitChain
	//	*Response_Query
	//	*Response_BeginBlock
	//	*Response_CheckTx
	//	*Response_DeliverTx
	//	*Response_EndBlock
	//	*Response_Commit
	Value isResponse_Value `protobuf_oneof:"value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Exception struct {
	Exception *ResponseException `protobuf:"bytes,1,opt,name=exception,oneof"`
}
type Response_Echo struct {
	Echo *ResponseEcho `protobuf:"bytes,2,opt,name=echo,oneof"`
}
type Response_Flush struct {
	Flush *ResponseFlush `protobuf:"bytes,3,opt,name=flush,oneof"`
}
type Response_Info struct {
	Info *ResponseInfo `protobuf:"bytes,4,opt,name=info,oneof"`
}
type Response_SetOption struct {
	SetOption *ResponseSetOption `protobuf:"bytes,5,opt,name=set_option,json=setOption,oneof"`
}
type Response_InitChain struct {
	InitChain *ResponseInitChain `protobuf:"bytes,6,opt,name=init_chain,json=initChain,oneof"`
}
type Response_Query struct {
	Query *ResponseQuery `protobuf:"bytes,7,opt,name=query,oneof"`
}
type Response_BeginBlock struct {
	BeginBlock *ResponseBeginBlock `protobuf:"bytes,8,opt,name=begin_block,json=beginBlock,oneof"`
}
type Response_CheckTx struct {
	CheckTx *ResponseCheckTx `protobuf:"bytes,9,opt,name=check_tx,json=checkTx,oneof"`
}
type Response_DeliverTx struct {
	DeliverTx *ResponseDeliverTx `protobuf:"bytes,10,opt,name=deliver_tx,json=deliverTx,oneof"`
}
type Response_EndBlock struct {
	EndBlock *ResponseEndBlock `protobuf:"bytes,11,opt,name=end_block,json=endBlock,oneof"`
}
type Response_Commit struct {
	Commit *ResponseCommit `protobuf:"bytes,12,opt,name=commit,oneof"`
}

func (*Response_Exception) isResponse_Value()  {}
func (*Response_Echo) isResponse_Value()       {}
func (*Response_Flush) isResponse_Value()      {}
func (*Response_Info) isResponse_Value()       {}
func (*Response_SetOption) isResponse_Value()  {}
func (*Response_InitChain) isResponse_Value()  {}
func (*Response_Query) isResponse_Value()      {}
func (*Response_BeginBlock) isResponse_Value() {}
func (*Response_CheckTx) isResponse_Value()    {}
func (*Response_DeliverTx) isResponse_Value()  {}
func (*Response_EndBlock) isResponse_Value()   {}
func (*Response_Commit) isResponse_Value()     {}

func (m *Response) GetValue() isResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetException() *ResponseException {
	if x, ok := m.GetValue().(*Response_Exception); ok {
		return x.Exception
	}
	return nil
}

func (m *Response) GetEcho() *ResponseEcho {
	if x, ok := m.GetValue().(*Response_Echo); ok {
		return x.Echo
	}
	return nil
}

func (m *Response) GetFlush() *ResponseFlush {
	if x, ok := m.GetValue().(*Response_Flush); ok {
		return x.Flush
	}
	return nil
}

func (m *Response) GetInfo() *ResponseInfo {
	if x, ok := m.GetValue().(*Response_Info); ok {
		return x.Info
	}
	return nil
}

func (m *Response) GetSetOption() *ResponseSetOption {
	if x, ok := m.GetValue().(*Response_SetOption); ok {
		return x.SetOption
	}
	return nil
}

func (m *Response) GetInitChain() *ResponseInitChain {
	if x, ok := m.GetValue().(*Response_InitChain); ok {
		return x.InitChain
	}
	return nil
}

func (m *Response) GetQuery() *ResponseQuery {
	if x, ok := m.GetValue().(*Response_Query); ok {
		return x.Query
	}
	return nil
}

func (m *Response) GetBeginBlock() *ResponseBeginBlock {
	if x, ok := m.GetValue().(*Response_BeginBlock); ok {
		return x.BeginBlock
	}
	return nil
}

func (m *Response) GetCheckTx() *ResponseCheckTx {
	if x, ok := m.GetValue().(*Response_CheckTx); ok {
		return x.CheckTx
	}
	return nil
}

func (m *Response) GetDeliverTx() *ResponseDeliverTx {
	if x, ok := m.GetValue().(*Response_DeliverTx); ok {
		return x.DeliverTx
	}
	return nil
}

func (m *Response) GetEndBlock() *ResponseEndBlock {
	if x, ok := m.GetValue().(*Response_EndBlock); ok {
		return x.EndBlock
	}
	return nil
}

func (m *Response) GetCommit() *ResponseCommit {
	if x, ok := m.GetValue().(*Response_Commit); ok {
		return x.Commit
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Exception)(nil),
		(*Response_Echo)(nil),
		(*Response_Flush)(nil),
		(*Response_Info)(nil),
		(*Response_SetOption)(nil),
		(*Response_InitChain)(nil),
		(*Response_Query)(nil),
		(*Response_BeginBlock)(nil),
		(*Response_CheckTx)(nil),
		(*Response_DeliverTx)(nil),
		(*Response_EndBlock)(nil),
		(*Response_Commit)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// value
	switch x := m.Value.(type) {
	case *Response_Exception:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exception); err != nil {
			return err
		}
	case *Response_Echo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Echo); err != nil {
			return err
		}
	case *Response_Flush:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Flush); err != nil {
			return err
		}
	case *Response_Info:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *Response_SetOption:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetOption); err != nil {
			return err
		}
	case *Response_InitChain:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitChain); err != nil {
			return err
		}
	case *Response_Query:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case *Response_BeginBlock:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BeginBlock); err != nil {
			return err
		}
	case *Response_CheckTx:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckTx); err != nil {
			return err
		}
	case *Response_DeliverTx:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeliverTx); err != nil {
			return err
		}
	case *Response_EndBlock:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EndBlock); err != nil {
			return err
		}
	case *Response_Commit:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Value has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // value.exception
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseException)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Exception{msg}
		return true, err
	case 2: // value.echo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseEcho)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Echo{msg}
		return true, err
	case 3: // value.flush
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseFlush)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Flush{msg}
		return true, err
	case 4: // value.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseInfo)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Info{msg}
		return true, err
	case 5: // value.set_option
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseSetOption)
		err := b.DecodeMessage(msg)
		m.Value = &Response_SetOption{msg}
		return true, err
	case 6: // value.init_chain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseInitChain)
		err := b.DecodeMessage(msg)
		m.Value = &Response_InitChain{msg}
		return true, err
	case 7: // value.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseQuery)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Query{msg}
		return true, err
	case 8: // value.begin_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseBeginBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Response_BeginBlock{msg}
		return true, err
	case 9: // value.check_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseCheckTx)
		err := b.DecodeMessage(msg)
		m.Value = &Response_CheckTx{msg}
		return true, err
	case 10: // value.deliver_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseDeliverTx)
		err := b.DecodeMessage(msg)
		m.Value = &Response_DeliverTx{msg}
		return true, err
	case 11: // value.end_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseEndBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Response_EndBlock{msg}
		return true, err
	case 12: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseCommit)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Commit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// value
	switch x := m.Value.(type) {
	case *Response_Exception:
		s := proto.Size(x.Exception)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Echo:
		s := proto.Size(x.Echo)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Flush:
		s := proto.Size(x.Flush)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Info:
		s := proto.Size(x.Info)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_SetOption:
		s := proto.Size(x.SetOption)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_InitChain:
		s := proto.Size(x.InitChain)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Query:
		s := proto.Size(x.Query)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BeginBlock:
		s := proto.Size(x.BeginBlock)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_CheckTx:
		s := proto.Size(x.CheckTx)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_DeliverTx:
		s := proto.Size(x.DeliverTx)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_EndBlock:
		s := proto.Size(x.EndBlock)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Commit:
		s := proto.Size(x.Commit)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// nondeterministic
type ResponseException struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseException) Reset()                    { *m = ResponseException{} }
func (m *ResponseException) String() string            { return proto.CompactTextString(m) }
func (*ResponseException) ProtoMessage()               {}
func (*ResponseException) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ResponseException) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseEcho struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ResponseEcho) Reset()                    { *m = ResponseEcho{} }
func (m *ResponseEcho) String() string            { return proto.CompactTextString(m) }
func (*ResponseEcho) ProtoMessage()               {}
func (*ResponseEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ResponseEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseFlush struct {
}

func (m *ResponseFlush) Reset()                    { *m = ResponseFlush{} }
func (m *ResponseFlush) String() string            { return proto.CompactTextString(m) }
func (*ResponseFlush) ProtoMessage()               {}
func (*ResponseFlush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ResponseInfo struct {
	Data             string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Version          string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	LastBlockHeight  int64  `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight" json:"last_block_height,omitempty"`
	LastBlockAppHash []byte `protobuf:"bytes,4,opt,name=last_block_app_hash,json=lastBlockAppHash,proto3" json:"last_block_app_hash,omitempty"`
}

func (m *ResponseInfo) Reset()                    { *m = ResponseInfo{} }
func (m *ResponseInfo) String() string            { return proto.CompactTextString(m) }
func (*ResponseInfo) ProtoMessage()               {}
func (*ResponseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ResponseInfo) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResponseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ResponseInfo) GetLastBlockHeight() int64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *ResponseInfo) GetLastBlockAppHash() []byte {
	if m != nil {
		return m.LastBlockAppHash
	}
	return nil
}

// nondeterministic
type ResponseSetOption struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// bytes data = 2;
	Log  string `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	Info string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
}

func (m *ResponseSetOption) Reset()                    { *m = ResponseSetOption{} }
func (m *ResponseSetOption) String() string            { return proto.CompactTextString(m) }
func (*ResponseSetOption) ProtoMessage()               {}
func (*ResponseSetOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ResponseSetOption) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseSetOption) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseSetOption) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ResponseInitChain struct {
}

func (m *ResponseInitChain) Reset()                    { *m = ResponseInitChain{} }
func (m *ResponseInitChain) String() string            { return proto.CompactTextString(m) }
func (*ResponseInitChain) ProtoMessage()               {}
func (*ResponseInitChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ResponseQuery struct {
	Code uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// bytes data = 2; // use "value" instead.
	Log    string `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	Info   string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Index  int64  `protobuf:"varint,5,opt,name=index" json:"index,omitempty"`
	Key    []byte `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	Proof  []byte `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
	Height int64  `protobuf:"varint,9,opt,name=height" json:"height,omitempty"`
}

func (m *ResponseQuery) Reset()                    { *m = ResponseQuery{} }
func (m *ResponseQuery) String() string            { return proto.CompactTextString(m) }
func (*ResponseQuery) ProtoMessage()               {}
func (*ResponseQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ResponseQuery) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseQuery) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseQuery) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseQuery) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ResponseQuery) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ResponseQuery) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResponseQuery) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *ResponseQuery) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ResponseBeginBlock struct {
}

func (m *ResponseBeginBlock) Reset()                    { *m = ResponseBeginBlock{} }
func (m *ResponseBeginBlock) String() string            { return proto.CompactTextString(m) }
func (*ResponseBeginBlock) ProtoMessage()               {}
func (*ResponseBeginBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type ResponseCheckTx struct {
	Code      uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log       string `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	Info      string `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	GasWanted int64  `protobuf:"varint,5,opt,name=gas_wanted,json=gasWanted" json:"gas_wanted,omitempty"`
	// int64 gas_used = 6;
	Tags  []*common.KVPair `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Fee   *common.KI64Pair `protobuf:"bytes,8,opt,name=fee" json:"fee,omitempty"`
	Error string           `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseCheckTx) Reset()                    { *m = ResponseCheckTx{} }
func (m *ResponseCheckTx) String() string            { return proto.CompactTextString(m) }
func (*ResponseCheckTx) ProtoMessage()               {}
func (*ResponseCheckTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ResponseCheckTx) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCheckTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseCheckTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseCheckTx) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseCheckTx) GetGasWanted() int64 {
	if m != nil {
		return m.GasWanted
	}
	return 0
}

func (m *ResponseCheckTx) GetTags() []*common.KVPair {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ResponseCheckTx) GetFee() *common.KI64Pair {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *ResponseCheckTx) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseDeliverTx struct {
	Code      uint32           `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data      []byte           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log       string           `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	Info      string           `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	GasWanted int64            `protobuf:"varint,5,opt,name=gas_wanted,json=gasWanted" json:"gas_wanted,omitempty"`
	GasUsed   int64            `protobuf:"varint,6,opt,name=gas_used,json=gasUsed" json:"gas_used,omitempty"`
	Tags      []*common.KVPair `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	// common.KI64Pair fee = 8;
	Error string `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseDeliverTx) Reset()                    { *m = ResponseDeliverTx{} }
func (m *ResponseDeliverTx) String() string            { return proto.CompactTextString(m) }
func (*ResponseDeliverTx) ProtoMessage()               {}
func (*ResponseDeliverTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ResponseDeliverTx) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseDeliverTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseDeliverTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ResponseDeliverTx) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseDeliverTx) GetGasWanted() int64 {
	if m != nil {
		return m.GasWanted
	}
	return 0
}

func (m *ResponseDeliverTx) GetGasUsed() int64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *ResponseDeliverTx) GetTags() []*common.KVPair {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ResponseDeliverTx) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseEndBlock struct {
	ValidatorUpdates      []*Validator     `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates" json:"validator_updates,omitempty"`
	ConsensusParamUpdates *ConsensusParams `protobuf:"bytes,2,opt,name=consensus_param_updates,json=consensusParamUpdates" json:"consensus_param_updates,omitempty"`
}

func (m *ResponseEndBlock) Reset()                    { *m = ResponseEndBlock{} }
func (m *ResponseEndBlock) String() string            { return proto.CompactTextString(m) }
func (*ResponseEndBlock) ProtoMessage()               {}
func (*ResponseEndBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ResponseEndBlock) GetValidatorUpdates() []*Validator {
	if m != nil {
		return m.ValidatorUpdates
	}
	return nil
}

func (m *ResponseEndBlock) GetConsensusParamUpdates() *ConsensusParams {
	if m != nil {
		return m.ConsensusParamUpdates
	}
	return nil
}

type ResponseCommit struct {
	// reserve 1
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ResponseCommit) Reset()                    { *m = ResponseCommit{} }
func (m *ResponseCommit) String() string            { return proto.CompactTextString(m) }
func (*ResponseCommit) ProtoMessage()               {}
func (*ResponseCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ResponseCommit) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ConsensusParams contains all consensus-relevant parameters
// that can be adjusted by the abci app
type ConsensusParams struct {
	BlockSize   *BlockSize   `protobuf:"bytes,1,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
	TxSize      *TxSize      `protobuf:"bytes,2,opt,name=tx_size,json=txSize" json:"tx_size,omitempty"`
	BlockGossip *BlockGossip `protobuf:"bytes,3,opt,name=block_gossip,json=blockGossip" json:"block_gossip,omitempty"`
}

func (m *ConsensusParams) Reset()                    { *m = ConsensusParams{} }
func (m *ConsensusParams) String() string            { return proto.CompactTextString(m) }
func (*ConsensusParams) ProtoMessage()               {}
func (*ConsensusParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ConsensusParams) GetBlockSize() *BlockSize {
	if m != nil {
		return m.BlockSize
	}
	return nil
}

func (m *ConsensusParams) GetTxSize() *TxSize {
	if m != nil {
		return m.TxSize
	}
	return nil
}

func (m *ConsensusParams) GetBlockGossip() *BlockGossip {
	if m != nil {
		return m.BlockGossip
	}
	return nil
}

// BlockSize contain limits on the block size.
type BlockSize struct {
	MaxBytes int32 `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes" json:"max_bytes,omitempty"`
	MaxTxs   int32 `protobuf:"varint,2,opt,name=max_txs,json=maxTxs" json:"max_txs,omitempty"`
	MaxGas   int64 `protobuf:"varint,3,opt,name=max_gas,json=maxGas" json:"max_gas,omitempty"`
}

func (m *BlockSize) Reset()                    { *m = BlockSize{} }
func (m *BlockSize) String() string            { return proto.CompactTextString(m) }
func (*BlockSize) ProtoMessage()               {}
func (*BlockSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *BlockSize) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

func (m *BlockSize) GetMaxTxs() int32 {
	if m != nil {
		return m.MaxTxs
	}
	return 0
}

func (m *BlockSize) GetMaxGas() int64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

// TxSize contain limits on the tx size.
type TxSize struct {
	MaxBytes int32 `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes" json:"max_bytes,omitempty"`
	MaxGas   int64 `protobuf:"varint,2,opt,name=max_gas,json=maxGas" json:"max_gas,omitempty"`
}

func (m *TxSize) Reset()                    { *m = TxSize{} }
func (m *TxSize) String() string            { return proto.CompactTextString(m) }
func (*TxSize) ProtoMessage()               {}
func (*TxSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *TxSize) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

func (m *TxSize) GetMaxGas() int64 {
	if m != nil {
		return m.MaxGas
	}
	return 0
}

// BlockGossip determine consensus critical
// elements of how blocks are gossiped
type BlockGossip struct {
	// Note: must not be 0
	BlockPartSizeBytes int32 `protobuf:"varint,1,opt,name=block_part_size_bytes,json=blockPartSizeBytes" json:"block_part_size_bytes,omitempty"`
}

func (m *BlockGossip) Reset()                    { *m = BlockGossip{} }
func (m *BlockGossip) String() string            { return proto.CompactTextString(m) }
func (*BlockGossip) ProtoMessage()               {}
func (*BlockGossip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *BlockGossip) GetBlockPartSizeBytes() int32 {
	if m != nil {
		return m.BlockPartSizeBytes
	}
	return 0
}

type Header struct {
	ChainId        string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Height         int64    `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Time           int64    `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	NumTxs         int32    `protobuf:"varint,4,opt,name=num_txs,json=numTxs" json:"num_txs,omitempty"`
	LastBlockId    *BlockID `protobuf:"bytes,5,opt,name=last_block_id,json=lastBlockId" json:"last_block_id,omitempty"`
	LastCommitHash []byte   `protobuf:"bytes,6,opt,name=last_commit_hash,json=lastCommitHash,proto3" json:"last_commit_hash,omitempty"`
	DataHash       []byte   `protobuf:"bytes,7,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	ValidatorsHash []byte   `protobuf:"bytes,8,opt,name=validators_hash,json=validatorsHash,proto3" json:"validators_hash,omitempty"`
	AppHash        []byte   `protobuf:"bytes,9,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *Header) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Header) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Header) GetNumTxs() int32 {
	if m != nil {
		return m.NumTxs
	}
	return 0
}

func (m *Header) GetLastBlockId() *BlockID {
	if m != nil {
		return m.LastBlockId
	}
	return nil
}

func (m *Header) GetLastCommitHash() []byte {
	if m != nil {
		return m.LastCommitHash
	}
	return nil
}

func (m *Header) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *Header) GetValidatorsHash() []byte {
	if m != nil {
		return m.ValidatorsHash
	}
	return nil
}

func (m *Header) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type BlockID struct {
	Hash  []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Parts *PartSetHeader `protobuf:"bytes,2,opt,name=parts" json:"parts,omitempty"`
}

func (m *BlockID) Reset()                    { *m = BlockID{} }
func (m *BlockID) String() string            { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()               {}
func (*BlockID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockID) GetParts() *PartSetHeader {
	if m != nil {
		return m.Parts
	}
	return nil
}

type PartSetHeader struct {
	Total int32  `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PartSetHeader) Reset()                    { *m = PartSetHeader{} }
func (m *PartSetHeader) String() string            { return proto.CompactTextString(m) }
func (*PartSetHeader) ProtoMessage()               {}
func (*PartSetHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PartSetHeader) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PartSetHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Validator struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Power  int64  `protobuf:"varint,2,opt,name=power" json:"power,omitempty"`
}

func (m *Validator) Reset()                    { *m = Validator{} }
func (m *Validator) String() string            { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()               {}
func (*Validator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type Evidence struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *Evidence) Reset()                    { *m = Evidence{} }
func (m *Evidence) String() string            { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()               {}
func (*Evidence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *Evidence) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Evidence) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "types.Request")
	proto.RegisterType((*RequestEcho)(nil), "types.RequestEcho")
	proto.RegisterType((*RequestFlush)(nil), "types.RequestFlush")
	proto.RegisterType((*RequestInfo)(nil), "types.RequestInfo")
	proto.RegisterType((*RequestSetOption)(nil), "types.RequestSetOption")
	proto.RegisterType((*RequestInitChain)(nil), "types.RequestInitChain")
	proto.RegisterType((*RequestQuery)(nil), "types.RequestQuery")
	proto.RegisterType((*RequestBeginBlock)(nil), "types.RequestBeginBlock")
	proto.RegisterType((*RequestCheckTx)(nil), "types.RequestCheckTx")
	proto.RegisterType((*RequestDeliverTx)(nil), "types.RequestDeliverTx")
	proto.RegisterType((*RequestEndBlock)(nil), "types.RequestEndBlock")
	proto.RegisterType((*RequestCommit)(nil), "types.RequestCommit")
	proto.RegisterType((*ResponseUpload)(nil), "types.ResponseUpload")
	proto.RegisterType((*IPFSReponse)(nil), "types.IPFSReponse")
	proto.RegisterType((*Response)(nil), "types.Response")
	proto.RegisterType((*ResponseException)(nil), "types.ResponseException")
	proto.RegisterType((*ResponseEcho)(nil), "types.ResponseEcho")
	proto.RegisterType((*ResponseFlush)(nil), "types.ResponseFlush")
	proto.RegisterType((*ResponseInfo)(nil), "types.ResponseInfo")
	proto.RegisterType((*ResponseSetOption)(nil), "types.ResponseSetOption")
	proto.RegisterType((*ResponseInitChain)(nil), "types.ResponseInitChain")
	proto.RegisterType((*ResponseQuery)(nil), "types.ResponseQuery")
	proto.RegisterType((*ResponseBeginBlock)(nil), "types.ResponseBeginBlock")
	proto.RegisterType((*ResponseCheckTx)(nil), "types.ResponseCheckTx")
	proto.RegisterType((*ResponseDeliverTx)(nil), "types.ResponseDeliverTx")
	proto.RegisterType((*ResponseEndBlock)(nil), "types.ResponseEndBlock")
	proto.RegisterType((*ResponseCommit)(nil), "types.ResponseCommit")
	proto.RegisterType((*ConsensusParams)(nil), "types.ConsensusParams")
	proto.RegisterType((*BlockSize)(nil), "types.BlockSize")
	proto.RegisterType((*TxSize)(nil), "types.TxSize")
	proto.RegisterType((*BlockGossip)(nil), "types.BlockGossip")
	proto.RegisterType((*Header)(nil), "types.Header")
	proto.RegisterType((*BlockID)(nil), "types.BlockID")
	proto.RegisterType((*PartSetHeader)(nil), "types.PartSetHeader")
	proto.RegisterType((*Validator)(nil), "types.Validator")
	proto.RegisterType((*Evidence)(nil), "types.Evidence")
	proto.RegisterEnum("types.CodeType", CodeType_name, CodeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ABCIApplication service

type ABCIApplicationClient interface {
	Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error)
	Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error)
	Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error)
	SetOption(ctx context.Context, in *RequestSetOption, opts ...grpc.CallOption) (*ResponseSetOption, error)
	DeliverTx(ctx context.Context, in *RequestDeliverTx, opts ...grpc.CallOption) (*ResponseDeliverTx, error)
	CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error)
	Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error)
	Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error)
	InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error)
	BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error)
	EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error)
}

type aBCIApplicationClient struct {
	cc *grpc.ClientConn
}

func NewABCIApplicationClient(cc *grpc.ClientConn) ABCIApplicationClient {
	return &aBCIApplicationClient{cc}
}

func (c *aBCIApplicationClient) Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error) {
	out := new(ResponseEcho)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error) {
	out := new(ResponseFlush)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/Flush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error) {
	out := new(ResponseInfo)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) SetOption(ctx context.Context, in *RequestSetOption, opts ...grpc.CallOption) (*ResponseSetOption, error) {
	out := new(ResponseSetOption)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/SetOption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) DeliverTx(ctx context.Context, in *RequestDeliverTx, opts ...grpc.CallOption) (*ResponseDeliverTx, error) {
	out := new(ResponseDeliverTx)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/DeliverTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error) {
	out := new(ResponseCheckTx)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/CheckTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error) {
	out := new(ResponseQuery)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error) {
	out := new(ResponseCommit)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/Commit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error) {
	out := new(ResponseInitChain)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/InitChain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error) {
	out := new(ResponseBeginBlock)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/BeginBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIApplicationClient) EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error) {
	out := new(ResponseEndBlock)
	err := grpc.Invoke(ctx, "/types.ABCIApplication/EndBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ABCIApplication service

type ABCIApplicationServer interface {
	Echo(context.Context, *RequestEcho) (*ResponseEcho, error)
	Flush(context.Context, *RequestFlush) (*ResponseFlush, error)
	Info(context.Context, *RequestInfo) (*ResponseInfo, error)
	SetOption(context.Context, *RequestSetOption) (*ResponseSetOption, error)
	DeliverTx(context.Context, *RequestDeliverTx) (*ResponseDeliverTx, error)
	CheckTx(context.Context, *RequestCheckTx) (*ResponseCheckTx, error)
	Query(context.Context, *RequestQuery) (*ResponseQuery, error)
	Commit(context.Context, *RequestCommit) (*ResponseCommit, error)
	InitChain(context.Context, *RequestInitChain) (*ResponseInitChain, error)
	BeginBlock(context.Context, *RequestBeginBlock) (*ResponseBeginBlock, error)
	EndBlock(context.Context, *RequestEndBlock) (*ResponseEndBlock, error)
}

func RegisterABCIApplicationServer(s *grpc.Server, srv ABCIApplicationServer) {
	s.RegisterService(&_ABCIApplication_serviceDesc, srv)
}

func _ABCIApplication_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEcho)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Echo(ctx, req.(*RequestEcho))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFlush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Flush(ctx, req.(*RequestFlush))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Info(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_SetOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSetOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).SetOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/SetOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).SetOption(ctx, req.(*RequestSetOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_DeliverTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeliverTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).DeliverTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/DeliverTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).DeliverTx(ctx, req.(*RequestDeliverTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_CheckTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).CheckTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/CheckTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).CheckTx(ctx, req.(*RequestCheckTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Query(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).Commit(ctx, req.(*RequestCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_InitChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).InitChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/InitChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).InitChain(ctx, req.(*RequestInitChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_BeginBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBeginBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).BeginBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/BeginBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).BeginBlock(ctx, req.(*RequestBeginBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIApplication_EndBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEndBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIApplicationServer).EndBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.ABCIApplication/EndBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIApplicationServer).EndBlock(ctx, req.(*RequestEndBlock))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABCIApplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.ABCIApplication",
	HandlerType: (*ABCIApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _ABCIApplication_Echo_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _ABCIApplication_Flush_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _ABCIApplication_Info_Handler,
		},
		{
			MethodName: "SetOption",
			Handler:    _ABCIApplication_SetOption_Handler,
		},
		{
			MethodName: "DeliverTx",
			Handler:    _ABCIApplication_DeliverTx_Handler,
		},
		{
			MethodName: "CheckTx",
			Handler:    _ABCIApplication_CheckTx_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ABCIApplication_Query_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _ABCIApplication_Commit_Handler,
		},
		{
			MethodName: "InitChain",
			Handler:    _ABCIApplication_InitChain_Handler,
		},
		{
			MethodName: "BeginBlock",
			Handler:    _ABCIApplication_BeginBlock_Handler,
		},
		{
			MethodName: "EndBlock",
			Handler:    _ABCIApplication_EndBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2013 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0xb7, 0xfe, 0x8b, 0x4f, 0xb6, 0x4c, 0x8f, 0x9d, 0x44, 0xd1, 0xa2, 0x48, 0x40, 0x14, 0x59,
	0x67, 0x93, 0xb5, 0xdb, 0x6c, 0x13, 0x24, 0xd9, 0x62, 0x51, 0xcb, 0x76, 0x62, 0x21, 0xed, 0xda,
	0xa5, 0xed, 0x2c, 0xd0, 0x8b, 0x30, 0x12, 0xc7, 0x12, 0x6b, 0x69, 0xc8, 0x90, 0x43, 0x47, 0xce,
	0x67, 0xd8, 0x7b, 0xcf, 0x3d, 0xf5, 0x13, 0xf4, 0x2b, 0x14, 0x2d, 0xfa, 0x1d, 0x72, 0xd8, 0x63,
	0x81, 0xa2, 0xf7, 0x9e, 0x8a, 0x37, 0x33, 0xa4, 0x48, 0x9a, 0x5a, 0x2c, 0xda, 0x62, 0x4f, 0xe4,
	0xcc, 0xfb, 0x33, 0xf3, 0x66, 0xde, 0xfc, 0x7e, 0x6f, 0x06, 0x5a, 0xe2, 0xda, 0x67, 0xe1, 0x8e,
	0x1f, 0x78, 0xc2, 0x23, 0x35, 0xd9, 0xe8, 0x7e, 0x3e, 0x76, 0xc5, 0x24, 0x1a, 0xee, 0x8c, 0xbc,
	0xd9, 0xee, 0xd8, 0x1b, 0x7b, 0xbb, 0x52, 0x3a, 0x8c, 0x2e, 0x64, 0x4b, 0x36, 0xe4, 0x9f, 0xb2,
	0xea, 0xee, 0xa6, 0xd4, 0x05, 0xe3, 0x0e, 0x0b, 0x66, 0x2e, 0x17, 0xbb, 0x62, 0x36, 0x75, 0x87,
	0xe1, 0xee, 0xc8, 0x9b, 0xcd, 0x3c, 0xbe, 0x9b, 0x1a, 0xc6, 0xfa, 0x4b, 0x15, 0x1a, 0x36, 0x7b,
	0x17, 0xb1, 0x50, 0x90, 0x6d, 0xa8, 0xb2, 0xd1, 0xc4, 0xeb, 0x94, 0xef, 0x97, 0xb6, 0x5b, 0x4f,
	0xc8, 0x8e, 0xd2, 0xd3, 0xd2, 0xc3, 0xd1, 0xc4, 0x3b, 0x5a, 0xb1, 0xa5, 0x06, 0x79, 0x04, 0xb5,
	0x8b, 0x69, 0x14, 0x4e, 0x3a, 0x15, 0xa9, 0xba, 0x99, 0x55, 0x7d, 0x85, 0xa2, 0xa3, 0x15, 0x5b,
	0xe9, 0xa0, 0x5b, 0x97, 0x5f, 0x78, 0x9d, 0x6a, 0x91, 0xdb, 0x3e, 0xbf, 0x90, 0x6e, 0x51, 0x83,
	0x3c, 0x07, 0x08, 0x99, 0x18, 0x78, 0xbe, 0x70, 0x3d, 0xde, 0xa9, 0x49, 0xfd, 0x3b, 0x59, 0xfd,
	0x53, 0x26, 0x8e, 0xa5, 0xf8, 0x68, 0xc5, 0x36, 0xc2, 0xb8, 0x81, 0x96, 0x2e, 0x77, 0xc5, 0x60,
	0x34, 0xa1, 0x2e, 0xef, 0xd4, 0x8b, 0x2c, 0xfb, 0xdc, 0x15, 0xfb, 0x28, 0x46, 0x4b, 0x37, 0x6e,
	0x60, 0x28, 0xef, 0x22, 0x16, 0x5c, 0x77, 0x1a, 0x45, 0xa1, 0xfc, 0x16, 0x45, 0x18, 0x8a, 0xd4,
	0x21, 0x5f, 0x42, 0x6b, 0xc8, 0xc6, 0x2e, 0x1f, 0x0c, 0xa7, 0xde, 0xe8, 0xb2, 0xd3, 0x94, 0x26,
	0x9d, 0xac, 0x49, 0x0f, 0x15, 0x7a, 0x28, 0x3f, 0x5a, 0xb1, 0x61, 0x98, 0xb4, 0xc8, 0x13, 0x68,
	0x8e, 0x26, 0x6c, 0x74, 0x39, 0x10, 0xf3, 0x8e, 0x21, 0x2d, 0x6f, 0x65, 0x2d, 0xf7, 0x51, 0x7a,
	0x36, 0x3f, 0x5a, 0xb1, 0x1b, 0x23, 0xf5, 0x8b, 0x71, 0x39, 0x6c, 0xea, 0x5e, 0xb1, 0x00, 0xad,
	0x36, 0x8b, 0xe2, 0x3a, 0x50, 0x72, 0x69, 0x67, 0x38, 0x71, 0x83, 0x3c, 0x05, 0x83, 0x71, 0x47,
	0x4f, 0xb4, 0x25, 0x0d, 0x6f, 0xe7, 0x76, 0x94, 0x3b, 0xf1, 0x34, 0x9b, 0x4c, 0xff, 0x93, 0x1d,
	0xa8, 0x63, 0x96, 0xb8, 0xa2, 0xb3, 0x2a, 0x6d, 0xb6, 0x72, 0x53, 0x94, 0xb2, 0xa3, 0x15, 0x5b,
	0x6b, 0xf5, 0x1a, 0x50, 0xbb, 0xa2, 0xd3, 0x88, 0x59, 0x9f, 0x42, 0x2b, 0x95, 0x29, 0xa4, 0x03,
	0x8d, 0x19, 0x0b, 0x43, 0x3a, 0x66, 0x9d, 0xd2, 0xfd, 0xd2, 0xb6, 0x61, 0xc7, 0x4d, 0xab, 0x0d,
	0xab, 0xe9, 0x3c, 0x49, 0x19, 0x62, 0x2e, 0xa0, 0xe1, 0x15, 0x0b, 0x42, 0x4c, 0x00, 0x6d, 0xa8,
	0x9b, 0xd6, 0x4b, 0x30, 0xf3, 0x49, 0x40, 0x4c, 0xa8, 0x5c, 0xb2, 0x6b, 0xad, 0x89, 0xbf, 0x64,
	0x4b, 0x4f, 0x48, 0x66, 0xb1, 0x61, 0xeb, 0xd9, 0x05, 0x89, 0x6d, 0x92, 0x06, 0xe4, 0x19, 0xc0,
	0x15, 0x9d, 0xba, 0x0e, 0x15, 0x5e, 0x10, 0x76, 0x4a, 0xf7, 0x2b, 0xdb, 0xad, 0x27, 0xa6, 0x0e,
	0xf7, 0x6d, 0x2c, 0xe8, 0x55, 0xff, 0xfa, 0xf1, 0xde, 0x8a, 0x9d, 0xd2, 0x24, 0x0f, 0x60, 0x9d,
	0xfa, 0xfe, 0x20, 0x14, 0x54, 0xb0, 0xc1, 0xf0, 0x5a, 0xb0, 0x50, 0x8e, 0xb5, 0x6a, 0xaf, 0x51,
	0xdf, 0x3f, 0xc5, 0xde, 0x1e, 0x76, 0x5a, 0x4e, 0x12, 0xa8, 0xcc, 0x22, 0x42, 0xa0, 0xea, 0x50,
	0x41, 0xe5, 0x64, 0x57, 0x6d, 0xf9, 0x8f, 0x7d, 0x3e, 0x15, 0x13, 0x3d, 0x59, 0xf9, 0x4f, 0x6e,
	0x43, 0x7d, 0xc2, 0xdc, 0xf1, 0x44, 0xc8, 0xd3, 0x55, 0xb1, 0x75, 0x0b, 0x23, 0xf3, 0x03, 0xef,
	0x8a, 0xc9, 0x83, 0xd4, 0xb4, 0x55, 0xc3, 0xfa, 0x7b, 0x09, 0x36, 0x6e, 0x64, 0x1e, 0xfa, 0x9d,
	0xd0, 0x70, 0x12, 0x8f, 0x85, 0xff, 0xe4, 0x11, 0xfa, 0xa5, 0x0e, 0x0b, 0xf4, 0x01, 0x5f, 0xd3,
	0xb1, 0x1e, 0xc9, 0x4e, 0x1d, 0xa8, 0x56, 0x21, 0x8f, 0x60, 0x83, 0x0e, 0x43, 0xc6, 0xc5, 0x20,
	0xb5, 0x46, 0x95, 0xfb, 0x95, 0xed, 0x9a, 0x6d, 0x2a, 0xc1, 0xdb, 0xc5, 0x8a, 0x1c, 0xc1, 0xd6,
	0xf0, 0xfa, 0x03, 0xe5, 0xc2, 0xe5, 0x2c, 0xad, 0x5f, 0x95, 0x6b, 0xba, 0xae, 0xc7, 0x39, 0xbc,
	0x72, 0x1d, 0xc6, 0x47, 0x4c, 0x8f, 0xb4, 0x99, 0x98, 0x2c, 0x3c, 0x59, 0xf7, 0xa1, 0x9d, 0x3d,
	0x0c, 0xa4, 0x0d, 0x65, 0x31, 0xd7, 0x71, 0x94, 0xc5, 0xdc, 0xb2, 0x92, 0x9d, 0x4c, 0x12, 0xff,
	0x86, 0xce, 0x43, 0x58, 0xcf, 0xe5, 0x78, 0x6a, 0x51, 0x4b, 0xe9, 0x45, 0xb5, 0xd6, 0x61, 0x2d,
	0x93, 0xda, 0xd6, 0x37, 0x38, 0x83, 0xd0, 0xf7, 0x78, 0xc8, 0xce, 0xfd, 0xa9, 0x47, 0x1d, 0xf2,
	0x08, 0x9a, 0x23, 0xcf, 0x61, 0x18, 0x84, 0x34, 0x6e, 0x27, 0x11, 0xed, 0x7b, 0x0e, 0x3b, 0xbb,
	0xf6, 0x99, 0x9d, 0x28, 0xa4, 0xf3, 0xbe, 0x9c, 0xcd, 0xfb, 0x33, 0x68, 0xf5, 0x4f, 0x5e, 0x9d,
	0xda, 0x4c, 0xfa, 0xfe, 0x7f, 0x79, 0xfd, 0xb6, 0x06, 0xcd, 0x78, 0xbe, 0xe4, 0x39, 0x18, 0x6c,
	0x3e, 0x62, 0x0a, 0x3e, 0x4b, 0x39, 0x70, 0x52, 0x3a, 0x87, 0xb1, 0x1c, 0xd1, 0x22, 0x51, 0x26,
	0x0f, 0x33, 0xd0, 0xbf, 0x99, 0x37, 0x4a, 0x63, 0xff, 0xe3, 0x2c, 0xf6, 0x6f, 0xe5, 0x74, 0x73,
	0xe0, 0xff, 0x30, 0x03, 0xfe, 0x79, 0xc7, 0x19, 0xf4, 0x7f, 0x51, 0x80, 0xfe, 0xf9, 0xe9, 0x2f,
	0x81, 0xff, 0x17, 0x05, 0xf0, 0xdf, 0xb9, 0x31, 0x56, 0x21, 0xfe, 0x3f, 0xce, 0xe2, 0x7f, 0x3e,
	0x9c, 0x1c, 0x01, 0xfc, 0xb2, 0x88, 0x00, 0xee, 0xe6, 0x6c, 0x96, 0x32, 0xc0, 0x17, 0x37, 0x18,
	0xe0, 0x76, 0xce, 0xb4, 0x80, 0x02, 0x5e, 0x64, 0x28, 0x00, 0x0a, 0x63, 0x5b, 0xc2, 0x01, 0xcf,
	0x6e, 0x72, 0xc0, 0x9d, 0xfc, 0xd6, 0x16, 0x91, 0xc0, 0x6e, 0x8e, 0x04, 0x6e, 0xe5, 0x67, 0xb9,
	0x94, 0x05, 0x1e, 0x22, 0x18, 0xe5, 0x32, 0x0d, 0x81, 0x8b, 0x05, 0x81, 0x17, 0x68, 0x98, 0x56,
	0x0d, 0x6b, 0x1b, 0xe1, 0x71, 0x91, 0x5f, 0xdf, 0xc3, 0x18, 0xf2, 0x8c, 0xa6, 0xb2, 0xcb, 0xfa,
	0x43, 0x69, 0x61, 0x2b, 0x49, 0x23, 0x0d, 0xad, 0x86, 0x86, 0xd6, 0x14, 0x91, 0x94, 0x33, 0x44,
	0x42, 0x3e, 0x83, 0x8d, 0x29, 0x0d, 0x85, 0x5a, 0x97, 0x41, 0x06, 0x6b, 0xd7, 0x51, 0xa0, 0x16,
	0x44, 0x81, 0xee, 0xe7, 0xb0, 0x99, 0xd2, 0x45, 0xdc, 0x97, 0xb8, 0x5a, 0x95, 0x58, 0x63, 0x26,
	0xda, 0x7b, 0xbe, 0x7f, 0x44, 0xc3, 0x89, 0xf5, 0x9b, 0x45, 0xfc, 0x0b, 0x92, 0x22, 0x50, 0xc5,
	0x93, 0x2c, 0x67, 0xb7, 0x66, 0xcb, 0x7f, 0x24, 0xae, 0xa9, 0x37, 0x96, 0xa3, 0x1a, 0x36, 0xfe,
	0xa2, 0x56, 0x72, 0x52, 0x0c, 0x75, 0x24, 0xac, 0xcd, 0x85, 0xbb, 0x24, 0x7d, 0xad, 0x3f, 0x97,
	0x16, 0xeb, 0x91, 0x30, 0xcb, 0x7f, 0x37, 0x00, 0x6e, 0x8d, 0xcb, 0x1d, 0x36, 0x97, 0xc7, 0xad,
	0x62, 0xab, 0x46, 0xcc, 0xaa, 0x75, 0x19, 0x64, 0x96, 0x55, 0x1b, 0xb2, 0x4f, 0x35, 0x34, 0x23,
	0x79, 0x17, 0xf2, 0x1c, 0xac, 0xda, 0xaa, 0x91, 0x82, 0x5a, 0x23, 0x03, 0xb5, 0x5b, 0x40, 0x6e,
	0x9e, 0x10, 0xeb, 0xdf, 0x25, 0x04, 0xeb, 0x4c, 0xf6, 0x17, 0xc6, 0x13, 0x6f, 0x71, 0x39, 0xc5,
	0x9e, 0x3f, 0x2c, 0xc6, 0x9f, 0x00, 0x8c, 0x69, 0x38, 0x78, 0x4f, 0xb9, 0x60, 0x8e, 0x0e, 0xd4,
	0x18, 0xd3, 0xf0, 0x1b, 0xd9, 0x41, 0x5e, 0x42, 0x55, 0xd0, 0x71, 0xd8, 0x69, 0x48, 0xb2, 0x6a,
	0xef, 0xa8, 0x22, 0x79, 0xe7, 0xcd, 0xdb, 0x13, 0xea, 0x06, 0xbd, 0xdb, 0xc8, 0x55, 0xff, 0xf8,
	0x78, 0xaf, 0x8d, 0x3a, 0x8f, 0xbd, 0x99, 0x2b, 0xd8, 0xcc, 0x17, 0xd7, 0xb6, 0xb4, 0x21, 0xdb,
	0x50, 0xb9, 0x60, 0x4c, 0xc3, 0x80, 0x99, 0x98, 0xf6, 0x9f, 0xfd, 0x42, 0x1a, 0x2b, 0xa2, 0x43,
	0x95, 0xc5, 0x19, 0x30, 0xd2, 0x67, 0xe0, 0x9f, 0xa5, 0xc5, 0x06, 0x2f, 0xe8, 0xec, 0x47, 0x0d,
	0xff, 0x2e, 0x34, 0x51, 0x1c, 0x85, 0xcc, 0x91, 0x1b, 0x5e, 0xb1, 0x1b, 0x63, 0x1a, 0x9e, 0x87,
	0xff, 0xe3, 0xca, 0x14, 0xc7, 0xfb, 0xa7, 0x12, 0xb2, 0x77, 0x16, 0x79, 0xc8, 0x3e, 0x6c, 0x24,
	0x35, 0xc3, 0x20, 0xf2, 0x1d, 0x8a, 0x15, 0xd5, 0xf7, 0x97, 0x63, 0x66, 0x62, 0x70, 0xae, 0xf4,
	0xc9, 0xd7, 0x70, 0x67, 0x84, 0x5e, 0x79, 0x18, 0x85, 0x03, 0x9f, 0x06, 0x74, 0x96, 0xb8, 0x2a,
	0x67, 0x90, 0x76, 0x3f, 0xd6, 0x3a, 0x41, 0xa5, 0xd0, 0xbe, 0x35, 0xca, 0x74, 0x68, 0x7f, 0xd6,
	0x4f, 0x17, 0x65, 0x80, 0x42, 0xbb, 0xa2, 0x1d, 0xb0, 0xfe, 0x58, 0x82, 0xf5, 0x9c, 0x43, 0xb2,
	0x0b, 0xa0, 0xc0, 0x22, 0x74, 0x3f, 0x30, 0xcd, 0xc2, 0x71, 0x1c, 0x32, 0xe0, 0x53, 0xf7, 0x03,
	0xb3, 0x8d, 0x61, 0xfc, 0x4b, 0x1e, 0x40, 0x43, 0xcc, 0x95, 0x76, 0xb6, 0x30, 0x3b, 0x9b, 0x4b,
	0xd5, 0xba, 0x90, 0x5f, 0xf2, 0x14, 0x56, 0x95, 0xe3, 0xb1, 0x17, 0x86, 0xae, 0xaf, 0xf9, 0x97,
	0xa4, 0x5d, 0xbf, 0x96, 0x12, 0xbb, 0x35, 0x5c, 0x34, 0xac, 0xdf, 0x81, 0x91, 0x0c, 0x4b, 0x3e,
	0x01, 0x63, 0x46, 0xe7, 0xba, 0x6a, 0xc5, 0xb9, 0xd5, 0xec, 0xe6, 0x8c, 0xce, 0x65, 0xc1, 0x4a,
	0xee, 0x40, 0x03, 0x85, 0x62, 0xae, 0xd6, 0xac, 0x66, 0xd7, 0x67, 0x74, 0x7e, 0x36, 0x4f, 0x04,
	0x63, 0x1a, 0xc6, 0x25, 0xe9, 0x8c, 0xce, 0x5f, 0xd3, 0xd0, 0xfa, 0x0a, 0xea, 0x6a, 0x92, 0x3f,
	0xc8, 0x31, 0xda, 0x97, 0x33, 0xf6, 0xbf, 0x82, 0x56, 0x6a, 0xde, 0xe4, 0xe7, 0x70, 0x4b, 0x45,
	0xe8, 0xd3, 0x40, 0xc8, 0x15, 0xc9, 0x38, 0x24, 0x52, 0x78, 0x42, 0x03, 0x81, 0x43, 0xaa, 0x22,
	0xfb, 0x6f, 0x65, 0xa8, 0xab, 0x02, 0x96, 0x3c, 0x40, 0x76, 0xa5, 0x2e, 0x1f, 0xb8, 0x8e, 0x22,
	0x82, 0x5e, 0xeb, 0xbb, 0x8f, 0xf7, 0x1a, 0x12, 0x34, 0xfb, 0x07, 0x48, 0xa8, 0xf8, 0xe3, 0xa4,
	0xf0, 0xa9, 0x9c, 0xa9, 0xaf, 0x09, 0x54, 0x85, 0x3b, 0x63, 0x3a, 0x44, 0xf9, 0x8f, 0x33, 0xe7,
	0xd1, 0x4c, 0x2e, 0x49, 0x55, 0x2d, 0x09, 0x8f, 0x66, 0xb8, 0x24, 0xaf, 0x61, 0x2d, 0xc5, 0x0b,
	0xae, 0xa3, 0xeb, 0x95, 0x76, 0x7a, 0x37, 0xfa, 0x07, 0xbd, 0x4d, 0x4c, 0xd7, 0xef, 0x3e, 0xde,
	0x6b, 0xfd, 0x3a, 0x66, 0x8a, 0xfe, 0x81, 0xdd, 0x4a, 0x68, 0xa3, 0xef, 0x90, 0x6d, 0x90, 0x2c,
	0x32, 0x50, 0x4c, 0xaa, 0xd8, 0x45, 0x01, 0x6f, 0x1b, 0xfb, 0x35, 0xd5, 0x62, 0xfd, 0xfe, 0x09,
	0x18, 0x98, 0x74, 0x4a, 0x45, 0xe1, 0x70, 0x13, 0x3b, 0xa4, 0xf0, 0x53, 0x58, 0x5f, 0x14, 0xde,
	0x4a, 0x45, 0x81, 0x72, 0x7b, 0xd1, 0x2d, 0x15, 0xef, 0x42, 0x33, 0x61, 0x31, 0x43, 0x6a, 0x34,
	0xa8, 0x26, 0xaf, 0x63, 0x68, 0xe8, 0x29, 0x16, 0xde, 0x1f, 0x7e, 0x06, 0x35, 0xdc, 0x97, 0xf8,
	0x40, 0xc5, 0x95, 0x92, 0xdc, 0x0f, 0x26, 0x32, 0xb7, 0x08, 0xa5, 0x68, 0xbd, 0x80, 0xb5, 0x8c,
	0x14, 0x51, 0x41, 0x78, 0x82, 0x4e, 0xf5, 0x86, 0xaa, 0x46, 0x32, 0x58, 0x79, 0x31, 0x98, 0xf5,
	0x12, 0x8c, 0xe4, 0xd0, 0xe3, 0x2e, 0xf8, 0xd1, 0x70, 0x10, 0xdf, 0xf4, 0x56, 0xed, 0xba, 0x1f,
	0x0d, 0xdf, 0x28, 0x5a, 0xf2, 0xbd, 0xf7, 0xfa, 0x46, 0x53, 0xb1, 0x55, 0xc3, 0xfa, 0x12, 0x9a,
	0xf1, 0x5d, 0x63, 0xb9, 0xe9, 0x92, 0x2c, 0xf8, 0xec, 0x5f, 0x65, 0x68, 0xc6, 0x15, 0x38, 0xa9,
	0x43, 0xf9, 0xf8, 0x8d, 0xb9, 0x42, 0x36, 0x60, 0xad, 0xcf, 0x05, 0x0b, 0x38, 0x9d, 0x1e, 0x22,
	0x90, 0x99, 0x25, 0xec, 0x3a, 0xe4, 0x23, 0xcf, 0x71, 0xf9, 0x58, 0x75, 0x95, 0xc9, 0x2a, 0x34,
	0x7b, 0xd4, 0xf9, 0xda, 0xe3, 0x23, 0x66, 0x56, 0x88, 0x09, 0xab, 0xe7, 0x9c, 0x46, 0x62, 0xe2,
	0x05, 0xee, 0x07, 0xe6, 0x98, 0x55, 0x72, 0x0b, 0x36, 0xfa, 0x3c, 0x8c, 0x2e, 0x2e, 0xdc, 0x91,
	0xcb, 0xb8, 0x78, 0x15, 0x71, 0x27, 0x34, 0x6b, 0x84, 0x40, 0xfb, 0x9c, 0x5f, 0x72, 0xef, 0x3d,
	0xd7, 0x37, 0x11, 0xb3, 0x4e, 0x3a, 0xb0, 0xd5, 0xdb, 0x7f, 0x75, 0x7a, 0x10, 0xf9, 0x53, 0x77,
	0x44, 0x05, 0xdb, 0x73, 0x9c, 0x80, 0x85, 0xa1, 0xc9, 0xd0, 0x09, 0x4a, 0xb2, 0x63, 0x5f, 0x90,
	0x2d, 0x30, 0xb1, 0xbb, 0xcf, 0xe5, 0x76, 0xf7, 0xb9, 0x1f, 0x09, 0xf3, 0xf7, 0xb1, 0xb2, 0xee,
	0x3d, 0x8e, 0x04, 0x76, 0x5f, 0xe6, 0xba, 0x4f, 0xe4, 0x82, 0x98, 0xd3, 0x78, 0x50, 0xdd, 0x7d,
	0xea, 0x8e, 0x39, 0x15, 0x51, 0xc0, 0x4c, 0x4e, 0x6e, 0x03, 0x41, 0x89, 0x9e, 0x66, 0x3c, 0x19,
	0x2f, 0x76, 0xa4, 0xfb, 0xb5, 0x23, 0x3f, 0xdf, 0x3d, 0x8d, 0xc6, 0x2e, 0x37, 0xdf, 0xc5, 0xdd,
	0x92, 0xfc, 0xd5, 0xdd, 0xea, 0xf8, 0x8d, 0x19, 0x3c, 0xf9, 0xb6, 0x06, 0xeb, 0x7b, 0xbd, 0xfd,
	0xfe, 0x9e, 0xaf, 0x82, 0xc5, 0x92, 0x69, 0x17, 0xaa, 0xb2, 0x28, 0x2c, 0x78, 0x84, 0xea, 0x16,
	0xdd, 0x4e, 0xc8, 0x13, 0xa8, 0xc9, 0xda, 0x90, 0x14, 0xbd, 0x45, 0x75, 0x0b, 0x2f, 0x29, 0x38,
	0x88, 0xaa, 0x1e, 0x6f, 0x3e, 0x49, 0x75, 0x8b, 0x6e, 0x2a, 0xe4, 0x2b, 0x30, 0x16, 0x55, 0xdd,
	0xb2, 0x87, 0xa9, 0xee, 0xd2, 0x3b, 0x0b, 0xda, 0x2f, 0x58, 0x7e, 0xd9, 0x33, 0x4e, 0x77, 0x69,
	0x71, 0x4f, 0x9e, 0x43, 0x23, 0x2e, 0x91, 0x8a, 0x9f, 0x8e, 0xba, 0x4b, 0xee, 0x13, 0xb8, 0x3c,
	0xaa, 0x54, 0x2c, 0x7a, 0xdf, 0xea, 0x16, 0x5e, 0x7a, 0xc8, 0x53, 0xa8, 0x6b, 0xea, 0x2b, 0x7c,
	0x04, 0xea, 0x16, 0xdf, 0x0a, 0x30, 0xc8, 0xc5, 0x1b, 0xcb, 0xb2, 0x37, 0xb8, 0xee, 0xd2, 0xdb,
	0x19, 0xd9, 0x03, 0x48, 0x3d, 0x64, 0x2c, 0x7d, 0x5c, 0xeb, 0x2e, 0xbf, 0x75, 0x11, 0x04, 0x80,
	0xe4, 0xe2, 0x5f, 0xfc, 0xe8, 0xd5, 0x5d, 0x76, 0x11, 0x1a, 0xd6, 0xe5, 0xc3, 0xe8, 0x17, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xc9, 0xe1, 0x87, 0x8e, 0x15, 0x00, 0x00,
}
